/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/components/BarramundiFish.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/BarramundiFish.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BarramundiFish.geometry} material={materials['7288_barramundi fish_col']} rotation={[-Math.PI, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/BarramundiFish.glb')
