/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/components/card.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/card.glb')
  return (
    <group
  scale={3.5}
  position={[0, -1.2, -0.05]}
  onPointerOver={() => hover(true)}
  onPointerOut={() => hover(false)}
  onPointerUp={(e) => {
    e.target.releasePointerCapture(e.pointerId);
    drag(false);
  }}
  onPointerDown={(e) => {
    e.target.setPointerCapture(e.pointerId);
    drag(new THREE.Vector3().copy(e.point).sub(vec.copy(card.current.translation())));
  }}
>
  <Model />
</group>

  )
}

useGLTF.preload('/card.glb')
