/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 coffee_beans.glb --transform 
Files: coffee_beans.glb [1.39MB] > C:\Users\rrodriguezm\Desktop\axel\rect\arwax_2.0\public\coffee_beans-transformed.glb [118.75KB] (91%)
Author: Yusuf Scott (https://sketchfab.com/yousefskout27)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-beans-33189f74a03a430abf9cfc373219e178
Title: coffee beans
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/coffee_beans-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.COFFEE_COFFEE_MAT_0.geometry} material={materials.COFFEE_MAT} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/coffee_beans-transformed.glb')
