/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 coffee2.glb --transform 
Files: coffee2.glb [854.15KB] > C:\Users\rrodriguezm\Desktop\axel\rect\arwax_2.0\public\coffee2-transformed.glb [154.51KB] (82%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/coffee2-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Hotspot_1" position={[0.02, 0, 0]} />
        <mesh name="Plastic_Cup_0" geometry={nodes.Plastic_Cup_0.geometry} material={materials.Plastic_Cup} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/coffee2-transformed.glb')
